version: "3.9"
services:
  sqlserver:
    build: .
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "SuaSenha123!"
      ACCEPT_EULA: "Y"
    restart: unless-stopped
